"""initial schema

Revision ID: cb814021f0d2
Revises: 
Create Date: 2026-06-30 19:34:51.877598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb814021f0d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_migration_meta',
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('migrated_at', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('memory_access', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_items',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('last_message', sa.String(length=512), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_updated_at'), ['updated_at'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_updated_at'), ['updated_at'], unique=False)

    op.create_table('marketplace_stats',
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('liked_by', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('marketplace_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_stats_type'), ['type'], unique=False)

    op.create_table('platform_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('adapter_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_instances_adapter_type'), ['adapter_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_instances_enable'), ['enable'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=1024), nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('selected_models', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.String(length=64), nullable=True),
    sa.Column('sub_markets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_sources_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_sources_type'), ['type'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('conv_id', sa.String(length=64), nullable=True),
    sa.Column('is_stream', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usage_records_provider'))

    op.drop_table('usage_records')
    with op.batch_alter_table('repo_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_sources_type'))
        batch_op.drop_index(batch_op.f('ix_repo_sources_enabled'))

    op.drop_table('repo_sources')
    op.drop_table('providers')
    with op.batch_alter_table('platform_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_instances_enable'))
        batch_op.drop_index(batch_op.f('ix_platform_instances_adapter_type'))

    op.drop_table('platform_instances')
    with op.batch_alter_table('marketplace_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_stats_type'))

    op.drop_table('marketplace_stats')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_updated_at'))

    op.drop_table('groups')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_agent_id'))

    op.drop_table('conversations')
    op.drop_table('config_items')
    op.drop_table('agents')
    op.drop_table('_migration_meta')
    # ### end Alembic commands ###
